language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.6
    - 7.0
    - 7.1

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
        # Test against Symfony LTS versions
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 7.1
          env: SYMFONY_VERSION=3.4.*

install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit -v
